### ISSUE TITLE
Differences to repmo and repeatable-motions

### ISSUE THREAD

**Issue by HaleTom** [vds2212/vim-remotions#3]
Would you please provide a quick summary of how this is different to repmo and repeatable-motions?

In which use cases would it be better to use this or one of the others?

**Comment by vds2212** [comment]
I'll do 👍

**Comment by HaleTom** [comment]
Adjacent to this, are you aware of any lua plugins that do similar?

It seems there was a Great Winter of repeatable motion plugins until you started on yours!

**Comment by vds2212** [comment]
I can make repmo work for standard Vim action.

But when the action are overridden by special mapping for a specific filetype  (e.g.: `]m]` [pythonsense](https://github.com/jeetsukumaran/vim-pythonsense)) then I have difficulties to make it working.

I have also some doubts that repmo will work well when you are dealing with multiple `filetype` that each have their own dedicated mapping for the same combination key (e.g. `]m` for `python`/[pythonsense](https://github.com/jeetsukumaran/vim-pythonsense) vs. `]m` for `markdown`/[vim-markdown](https://github.com/preservim/vim-markdown))

Can you make repmo working well in such situation?

**Comment by vds2212** [comment]
I have updated the readme.md file accordingly.
