### ISSUE TITLE
Some errors from time to time

### ISSUE THREAD

**Issue by eyalk11** [vds2212/vim-remotions#7]
I got these erros: 

```
Error detected while processing function <SNR>183_RepeatMotion:
line   15:
E1206: Dictionary required for argument 1

Error detected while processing function <SNR>183_RepeatMotion:
line   15:
E1206: Dictionary required for argument 1


```

I am not sure when.

**Comment by vds2212** [comment]
Thanks for the feedback! I'll analyze the code and search for a solution. Of course it would be nice if you could provide a way to reproduce the problem :-)

**Comment by vds2212** [comment]
I had a look at the code and it would help me to understand the problem if you could share with me your remotions configuration. In particular the way the `g:remotions_motions` value.

**Comment by vds2212** [comment]
I have push some changes to make the code more robust (or even to correct a bug). I believe it will solve your problem but since I can't reproduce it I can't be sure. I'll let the issue open until you confirm that the new version solves your problem :-)

**Comment by eyalk11** [comment]
OK, thanks!  I actually copied your configuration of lazy and used it.

**Comment by eyalk11** [comment]
Seems to be working. Thanks!

**Comment by vds2212** [comment]
Thanks for your fast feedback!
