### ISSUE TITLE
Customized keys

### ISSUE THREAD

**Issue by eyalk11** [vds2212/vim-remotions#8]
I didn't really delve into it .
I override `t` key with my mapping (save file) . However, `vim-remotion ` did take control over it, and return it to the default vim mapping. 

Also, 
I use a different key for backwards motion ( <c-/> )

Is it supported?

**Comment by vds2212** [comment]
Indeed remotion hijack `t` and `f` to know if they should be repeated by `;` and `,`. But you are right it should do that only if `t` and `f` are not overriden.

I'll fix that and let you know when I have a solution.

Thanks for testing remotion :-)

**Comment by vds2212** [comment]
I have created a new version (2.2) that do not overrides the `t`, `T`, `f` and `F` mapping if any. This should solve your problem (I reproduced the problem and verifies that the issue is solved). Feel free to reopen the issue if that is not the case for you :-)

**Comment by eyalk11** [comment]
OK.  First , it works . Thank you. 

Secondly, I would like that `;` would work as the default for `f` even though it is not implemented as usual.  Though actually it is really nice to have for me as repeating the last key already does the trick. 

Third , customizing the `;` and `,` is nth too ( I just override it in the plugin file).

**Comment by vds2212** [comment]
I'm not sure I understand correctly your demand. Maybe could you introduce a feature request with the desired behavior. To be sure to understand you correctly I would like to have (on a given example of buffer):
1. The proposed input (sequence of key)
2. The expected output

Thanks again for your feedback.
