### ISSUE TITLE
Why doesn't <S-F4> work for me?

### ISSUE THREAD

**Issue by eyalk11** [vds2212/vim-remotions#9]
Probably not your bug. 

I tried to add the pair 
```
{backword=rep('<s-F3>'), ,forward = rep('<s-F4>')}
```

```
local function rep(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end
```

And it didn't work. what did I do wrong?

**Comment by vds2212** [comment]
I suspect a misspelling `backword` instead of  `backward`.

**Comment by vds2212** [comment]
Did you tried (lua):
```lua
{ backward = '<S-F3>', forward = '<S-F4>' }
```
or (vimscript):
```vim
#{ backward : '<S-F3>', forward : '<S-F4>' }
```
I see three potential problems in your attempt:
1. backword should be replaced by backward
2. There are two consecutive `,`
3. The `rep` is not necessary

**Comment by vds2212** [comment]
I'm not able to reproduce the problem.
